DEVICE_PATH := device/hanvon/rk3566_eink

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a55
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_SUPPORTS_32_BIT_APPS := false
TARGET_BOARD_PLATFORM := rk356x
TARGET_BOOTLOADER_BOARD_NAME := rk30board
TARGET_NO_BOOTLOADER := true

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_KERNEL_IMAGE_NAME := kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOT_HEADER_VERSION := 2
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
TARGET_RECOVERY_INITRC := $(DEVICE_PATH)/recovery/root/init.recovery.rk30board.rc

BOARD_USES_METADATA_PARTITION := true
TW_INCLUDE_DYNAMIC_PARTITIONS := true
BOARD_SUPER_PARTITION_SIZE := 3263168512
BOARD_SUPER_PARTITION_GROUPS := rockchip_dynamic_partitions
BOARD_ROCKCHIP_DYNAMIC_PARTITIONS_SIZE := 3258974208
BOARD_ROCKCHIP_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm system_ext

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_ROTATION := 90
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := zh_CN
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_FBE := false
TW_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
TWRP_EVENT_LOGGING := true
TW_NO_SCREEN_BLANK := true

# This build adds a Rockchip /dev/ebc backend to minuitwrp. The stock kernel
# and DTB are deliberately reused; no experimental kernel is compiled here.
TW_HAS_ROCKCHIP_EBC := true
